In [18]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,6,7])
c=a+b
print(c)


[ 4  6  8 10 12]


In [19]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
b=[[9,8,7],[6,5,4],[3,2,1]]
np.add(a,b)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
print(np.trace(a))
print(np.trace(b))


15
15


In [8]:
np.matmul(a,b)

85

In [9]:
np.subtract(a,b)


array([-2, -2, -2, -2, -2])

In [10]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
print(a)
np.array(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.invert(a)


array([[ -2,  -3,  -4],
       [ -5,  -6,  -7],
       [ -8,  -9, -10]])

In [13]:
import numpy as np
list=[1,2,3,4,5]
print(list)

[1, 2, 3, 4, 5]


In [16]:
print(type(list))

<class 'list'>


In [17]:
import numpy as np
array=np.array([1,2,3])
print(type(array))

<class 'numpy.ndarray'>


In [22]:
import numpy as np
array = np.array([10, 20, 30, 40, 50])
print("sin values")
print(np.sin(array))

print("log values")
print(np.log(array))

print("log2()")
print(np.log2(array))

print("Exponential")
print(np.exp(array))


sin values
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
log values
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
log2()
[3.32192809 4.32192809 4.9068906  5.32192809 5.64385619]
Exponential
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
